"""update

Revision ID: 1970bd0c00c8
Revises: b72adda43c11
Create Date: 2026-03-25 17:22:51.710258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1970bd0c00c8'
down_revision: Union[str, Sequence[str], None] = 'b72adda43c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cards_owner_id_fkey'), 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'profiles', ['owner_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_owner_id_fkey'), 'cards', 'guilds', ['owner_id'], ['id'])
    # ### end Alembic commands ###
