"""update

Revision ID: 89bc62a8ebec
Revises: a532979c0234
Create Date: 2026-03-25 17:02:24.479836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bc62a8ebec'
down_revision: Union[str, Sequence[str], None] = 'a532979c0234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('guilds_leader_id_fkey'), 'guilds', type_='foreignkey')
    op.create_foreign_key(None, 'guilds', 'users', ['leader_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guilds', type_='foreignkey')
    op.create_foreign_key(op.f('guilds_leader_id_fkey'), 'guilds', 'guilds', ['leader_id'], ['id'])
    # ### end Alembic commands ###
