"""initial

Revision ID: a184c7a4a0a1
Revises: 
Create Date: 2026-03-25 16:15:53.707395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a184c7a4a0a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amulet_rarities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('chance_drop_on_fight', sa.Integer(), nullable=True),
    sa.Column('chance_drop_on_box', sa.Integer(), nullable=True),
    sa.Column('max_upgrade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amulet_rarities_id'), 'amulet_rarities', ['id'], unique=False)
    op.create_table('amulet_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('bonus_hp', sa.Float(), nullable=True),
    sa.Column('bonus_damage', sa.Float(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('sale_now', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('discount_now', sa.Boolean(), nullable=True),
    sa.Column('rarity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rarity_id'], ['amulet_rarities.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amulet_types_id'), 'amulet_types', ['id'], unique=False)
    op.create_table('amulets_in_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amulet_type_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('upgrades', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amulet_type_id'], ['amulet_types.id'], use_alter=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['owner_id'], ['guilds.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amulets_in_inventory_id'), 'amulets_in_inventory', ['id'], unique=False)
    op.create_table('battle_event_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('award', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_event_awards_id'), 'battle_event_awards', ['id'], unique=False)
    op.create_table('battle_event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_card_id', sa.Integer(), nullable=True),
    sa.Column('second_card_id', sa.Integer(), nullable=True),
    sa.Column('third_card_id', sa.Integer(), nullable=True),
    sa.Column('enemies', sa.JSON(), nullable=True),
    sa.Column('battle_progress', sa.JSON(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_card_id'], ['cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['second_card_id'], ['cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['third_card_id'], ['cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['guilds.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_event_participants_id'), 'battle_event_participants', ['id'], unique=False)
    op.create_table('card_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_card_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('rarity_id', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('sale_now', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('discount_now', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_card_id'], ['class_cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarity_cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['type_id'], ['type_cards.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_store_id'), 'card_store', ['id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('class_card_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Float(), nullable=False),
    sa.Column('damage', sa.Float(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience_bar', sa.Integer(), nullable=False),
    sa.Column('rarity_id', sa.Integer(), nullable=False),
    sa.Column('sale_status', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('enhancement', sa.Integer(), nullable=False),
    sa.Column('max_enhancement', sa.Integer(), nullable=False),
    sa.Column('merger', sa.Integer(), nullable=False),
    sa.Column('max_merger', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_card_id'], ['class_cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['owner_id'], ['guilds.id'], use_alter=True),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarity_cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['type_id'], ['type_cards.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_index(op.f('ix_cards_owner_id'), 'cards', ['owner_id'], unique=False)
    op.create_table('class_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('skill', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('description_for_history_fight', sa.String(length=500), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('chance_use', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_cards_id'), 'class_cards', ['id'], unique=False)
    op.create_table('experience_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('rarity', sa.String(length=3), nullable=True),
    sa.Column('experience_amount', sa.Integer(), nullable=True),
    sa.Column('chance_drop_on_fight', sa.Integer(), nullable=True),
    sa.Column('chance_drop_on_box', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('gold_for_use', sa.Integer(), nullable=True),
    sa.Column('sale_now', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_items_id'), 'experience_items', ['id'], unique=False)
    op.create_table('favorite_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_user_id'], ['guilds.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['guilds.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_users_id'), 'favorite_users', ['id'], unique=False)
    op.create_table('fight_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_and_time', sa.DateTime(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('loser_id', sa.Integer(), nullable=True),
    sa.Column('card_winner_id', sa.Integer(), nullable=True),
    sa.Column('card_loser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_loser_id'], ['cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['card_winner_id'], ['cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['loser_id'], ['guilds.id'], use_alter=True),
    sa.ForeignKeyConstraint(['winner_id'], ['guilds.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fight_history_id'), 'fight_history', ['id'], unique=False)
    op.create_table('guild_buffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_buffs_id'), 'guild_buffs', ['id'], unique=False)
    op.create_table('guilds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('number_of_participants', sa.Integer(), nullable=False),
    sa.Column('max_number_of_participants', sa.Integer(), nullable=False),
    sa.Column('guild_pic', sa.String(length=255), nullable=False),
    sa.Column('date_create', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('buff_id', sa.Integer(), nullable=False),
    sa.Column('date_last_change_buff', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buff_id'], ['guild_buffs.id'], use_alter=True),
    sa.ForeignKeyConstraint(['leader_id'], ['guilds.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guilds_id'), 'guilds', ['id'], unique=False)
    op.create_index(op.f('ix_guilds_name'), 'guilds', ['name'], unique=True)
    op.create_table('history_purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_and_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['experience_items.id'], use_alter=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['guilds.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_purchase_items_id'), 'history_purchase_items', ['id'], unique=False)
    op.create_table('history_receiving_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('date_and_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method_receiving', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['guilds.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_receiving_cards_id'), 'history_receiving_cards', ['id'], unique=False)
    op.create_table('initial_event_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_event_visit', sa.Integer(), nullable=True),
    sa.Column('type_award', sa.String(length=30), nullable=True),
    sa.Column('amount_or_rarity_award', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_initial_event_awards_id'), 'initial_event_awards', ['id'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('theme', sa.String(length=200), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('date_time_create', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_table('rarity_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=2), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('coefficient_damage_for_level', sa.Float(), nullable=False),
    sa.Column('coefficient_hp_for_level', sa.Float(), nullable=False),
    sa.Column('min_hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('min_damage', sa.Integer(), nullable=False),
    sa.Column('max_damage', sa.Integer(), nullable=False),
    sa.Column('drop_chance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rarity_cards_id'), 'rarity_cards', ['id'], unique=False)
    op.create_table('sale_user_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_and_time', sa.DateTime(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('salesman_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('transaction_buyer_id', sa.Integer(), nullable=True),
    sa.Column('transaction_salesman_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['guilds.id'], use_alter=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['salesman_id'], ['guilds.id'], use_alter=True),
    sa.ForeignKeyConstraint(['transaction_buyer_id'], ['transactions.id'], use_alter=True),
    sa.ForeignKeyConstraint(['transaction_salesman_id'], ['transactions.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_user_cards_id'), 'sale_user_cards', ['id'], unique=False)
    op.create_table('teams_template_for_battle_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_card_id', sa.Integer(), nullable=True),
    sa.Column('second_card_id', sa.Integer(), nullable=True),
    sa.Column('third_card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_card_id'], ['cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['second_card_id'], ['cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['third_card_id'], ['cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['guilds.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_template_for_battle_event_id'), 'teams_template_for_battle_event', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_and_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('before', sa.Integer(), nullable=False),
    sa.Column('after', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['guilds.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('type_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('better_id', sa.Integer(), nullable=True),
    sa.Column('worst_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['better_id'], ['type_cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['worst_id'], ['type_cards.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_cards_id'), 'type_cards', ['id'], unique=False)
    op.create_table('upgrade_items_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('amount_up', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('price_of_use', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upgrade_items_types_id'), 'upgrade_items_types', ['id'], unique=False)
    op.create_table('upgrade_items_users_in_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upgrade_item_type_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['guilds.id'], use_alter=True),
    sa.ForeignKeyConstraint(['upgrade_item_type_id'], ['upgrade_items_types.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upgrade_items_users_in_inventory_id'), 'upgrade_items_users_in_inventory', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('users_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['experience_items.id'], use_alter=True),
    sa.ForeignKeyConstraint(['owner_id'], ['guilds.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_inventory_id'), 'users_inventory', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('about_user', sa.Text(), nullable=True),
    sa.Column('gold', sa.BigInteger(), nullable=False),
    sa.Column('diamond', sa.BigInteger(), nullable=False),
    sa.Column('receiving_timer', sa.DateTime(), nullable=True),
    sa.Column('win', sa.Integer(), nullable=False),
    sa.Column('lose', sa.Integer(), nullable=False),
    sa.Column('current_card_id', sa.Integer(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=False),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.Column('guild_id', sa.Integer(), nullable=True),
    sa.Column('date_guild_accession', sa.Date(), nullable=True),
    sa.Column('guild_point', sa.Integer(), nullable=False),
    sa.Column('card_slots', sa.Integer(), nullable=False),
    sa.Column('amulet_slots', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience_bar', sa.Integer(), nullable=False),
    sa.Column('event_visit', sa.Integer(), nullable=False),
    sa.Column('date_event_visit', sa.Date(), nullable=True),
    sa.Column('pending_email', sa.String(length=254), nullable=True),
    sa.ForeignKeyConstraint(['current_card_id'], ['cards.id'], use_alter=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_users_inventory_id'), table_name='users_inventory')
    op.drop_table('users_inventory')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_upgrade_items_users_in_inventory_id'), table_name='upgrade_items_users_in_inventory')
    op.drop_table('upgrade_items_users_in_inventory')
    op.drop_index(op.f('ix_upgrade_items_types_id'), table_name='upgrade_items_types')
    op.drop_table('upgrade_items_types')
    op.drop_index(op.f('ix_type_cards_id'), table_name='type_cards')
    op.drop_table('type_cards')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_teams_template_for_battle_event_id'), table_name='teams_template_for_battle_event')
    op.drop_table('teams_template_for_battle_event')
    op.drop_index(op.f('ix_sale_user_cards_id'), table_name='sale_user_cards')
    op.drop_table('sale_user_cards')
    op.drop_index(op.f('ix_rarity_cards_id'), table_name='rarity_cards')
    op.drop_table('rarity_cards')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_initial_event_awards_id'), table_name='initial_event_awards')
    op.drop_table('initial_event_awards')
    op.drop_index(op.f('ix_history_receiving_cards_id'), table_name='history_receiving_cards')
    op.drop_table('history_receiving_cards')
    op.drop_index(op.f('ix_history_purchase_items_id'), table_name='history_purchase_items')
    op.drop_table('history_purchase_items')
    op.drop_index(op.f('ix_guilds_name'), table_name='guilds')
    op.drop_index(op.f('ix_guilds_id'), table_name='guilds')
    op.drop_table('guilds')
    op.drop_index(op.f('ix_guild_buffs_id'), table_name='guild_buffs')
    op.drop_table('guild_buffs')
    op.drop_index(op.f('ix_fight_history_id'), table_name='fight_history')
    op.drop_table('fight_history')
    op.drop_index(op.f('ix_favorite_users_id'), table_name='favorite_users')
    op.drop_table('favorite_users')
    op.drop_index(op.f('ix_experience_items_id'), table_name='experience_items')
    op.drop_table('experience_items')
    op.drop_index(op.f('ix_class_cards_id'), table_name='class_cards')
    op.drop_table('class_cards')
    op.drop_index(op.f('ix_cards_owner_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_card_store_id'), table_name='card_store')
    op.drop_table('card_store')
    op.drop_index(op.f('ix_battle_event_participants_id'), table_name='battle_event_participants')
    op.drop_table('battle_event_participants')
    op.drop_index(op.f('ix_battle_event_awards_id'), table_name='battle_event_awards')
    op.drop_table('battle_event_awards')
    op.drop_index(op.f('ix_amulets_in_inventory_id'), table_name='amulets_in_inventory')
    op.drop_table('amulets_in_inventory')
    op.drop_index(op.f('ix_amulet_types_id'), table_name='amulet_types')
    op.drop_table('amulet_types')
    op.drop_index(op.f('ix_amulet_rarities_id'), table_name='amulet_rarities')
    op.drop_table('amulet_rarities')
    # ### end Alembic commands ###
