"""initial

Revision ID: a532979c0234
Revises: a184c7a4a0a1
Create Date: 2026-03-25 16:56:17.398825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a532979c0234'
down_revision: Union[str, Sequence[str], None] = 'a184c7a4a0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'amulet_types', 'amulet_rarities', ['rarity_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'amulets_in_inventory', 'guilds', ['owner_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'amulets_in_inventory', 'amulet_types', ['amulet_type_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'amulets_in_inventory', 'cards', ['card_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'battle_event_participants', 'cards', ['third_card_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'battle_event_participants', 'cards', ['second_card_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'battle_event_participants', 'cards', ['first_card_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'battle_event_participants', 'guilds', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'card_store', 'type_cards', ['type_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'card_store', 'class_cards', ['class_card_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'card_store', 'rarity_cards', ['rarity_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'cards', 'rarity_cards', ['rarity_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'cards', 'guilds', ['owner_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'cards', 'type_cards', ['type_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'cards', 'class_cards', ['class_card_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'favorite_users', 'guilds', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'favorite_users', 'guilds', ['favorite_user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'fight_history', 'guilds', ['loser_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'fight_history', 'cards', ['card_winner_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'fight_history', 'cards', ['card_loser_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'fight_history', 'guilds', ['winner_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'guilds', 'guilds', ['leader_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'guilds', 'guild_buffs', ['buff_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'history_purchase_items', 'guilds', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'history_purchase_items', 'transactions', ['transaction_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'history_purchase_items', 'experience_items', ['item_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'history_receiving_cards', 'cards', ['card_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'history_receiving_cards', 'guilds', ['user_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'cards', ['current_card_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'profiles', 'guilds', ['guild_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'sale_user_cards', 'guilds', ['buyer_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'sale_user_cards', 'guilds', ['salesman_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'sale_user_cards', 'transactions', ['transaction_buyer_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'sale_user_cards', 'transactions', ['transaction_salesman_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'sale_user_cards', 'cards', ['card_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'teams_template_for_battle_event', 'cards', ['third_card_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'teams_template_for_battle_event', 'cards', ['second_card_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'teams_template_for_battle_event', 'guilds', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'teams_template_for_battle_event', 'cards', ['first_card_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'transactions', 'guilds', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'type_cards', 'type_cards', ['worst_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'type_cards', 'type_cards', ['better_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'upgrade_items_users_in_inventory', 'guilds', ['owner_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'upgrade_items_users_in_inventory', 'upgrade_items_types', ['upgrade_item_type_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'users_inventory', 'guilds', ['owner_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'users_inventory', 'experience_items', ['item_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_inventory', type_='foreignkey')
    op.drop_constraint(None, 'users_inventory', type_='foreignkey')
    op.drop_constraint(None, 'upgrade_items_users_in_inventory', type_='foreignkey')
    op.drop_constraint(None, 'upgrade_items_users_in_inventory', type_='foreignkey')
    op.drop_constraint(None, 'type_cards', type_='foreignkey')
    op.drop_constraint(None, 'type_cards', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'teams_template_for_battle_event', type_='foreignkey')
    op.drop_constraint(None, 'teams_template_for_battle_event', type_='foreignkey')
    op.drop_constraint(None, 'teams_template_for_battle_event', type_='foreignkey')
    op.drop_constraint(None, 'teams_template_for_battle_event', type_='foreignkey')
    op.drop_constraint(None, 'sale_user_cards', type_='foreignkey')
    op.drop_constraint(None, 'sale_user_cards', type_='foreignkey')
    op.drop_constraint(None, 'sale_user_cards', type_='foreignkey')
    op.drop_constraint(None, 'sale_user_cards', type_='foreignkey')
    op.drop_constraint(None, 'sale_user_cards', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'guilds', ['user_id'], ['id'])
    op.drop_constraint(None, 'history_receiving_cards', type_='foreignkey')
    op.drop_constraint(None, 'history_receiving_cards', type_='foreignkey')
    op.drop_constraint(None, 'history_purchase_items', type_='foreignkey')
    op.drop_constraint(None, 'history_purchase_items', type_='foreignkey')
    op.drop_constraint(None, 'history_purchase_items', type_='foreignkey')
    op.drop_constraint(None, 'guilds', type_='foreignkey')
    op.drop_constraint(None, 'guilds', type_='foreignkey')
    op.drop_constraint(None, 'fight_history', type_='foreignkey')
    op.drop_constraint(None, 'fight_history', type_='foreignkey')
    op.drop_constraint(None, 'fight_history', type_='foreignkey')
    op.drop_constraint(None, 'fight_history', type_='foreignkey')
    op.drop_constraint(None, 'favorite_users', type_='foreignkey')
    op.drop_constraint(None, 'favorite_users', type_='foreignkey')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_constraint(None, 'card_store', type_='foreignkey')
    op.drop_constraint(None, 'card_store', type_='foreignkey')
    op.drop_constraint(None, 'card_store', type_='foreignkey')
    op.drop_constraint(None, 'battle_event_participants', type_='foreignkey')
    op.drop_constraint(None, 'battle_event_participants', type_='foreignkey')
    op.drop_constraint(None, 'battle_event_participants', type_='foreignkey')
    op.drop_constraint(None, 'battle_event_participants', type_='foreignkey')
    op.drop_constraint(None, 'amulets_in_inventory', type_='foreignkey')
    op.drop_constraint(None, 'amulets_in_inventory', type_='foreignkey')
    op.drop_constraint(None, 'amulets_in_inventory', type_='foreignkey')
    op.drop_constraint(None, 'amulet_types', type_='foreignkey')
    # ### end Alembic commands ###
