"""initial

Revision ID: b72adda43c11
Revises: d73acba8a069
Create Date: 2026-03-25 17:21:23.594832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72adda43c11'
down_revision: Union[str, Sequence[str], None] = 'd73acba8a069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('amulets_in_inventory_owner_id_fkey'), 'amulets_in_inventory', type_='foreignkey')
    op.create_foreign_key(None, 'amulets_in_inventory', 'profiles', ['owner_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('battle_event_participants_user_id_fkey'), 'battle_event_participants', type_='foreignkey')
    op.create_foreign_key(None, 'battle_event_participants', 'profiles', ['user_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('favorite_users_favorite_user_id_fkey'), 'favorite_users', type_='foreignkey')
    op.drop_constraint(op.f('favorite_users_user_id_fkey'), 'favorite_users', type_='foreignkey')
    op.create_foreign_key(None, 'favorite_users', 'profiles', ['favorite_user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'favorite_users', 'profiles', ['user_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('fight_history_winner_id_fkey'), 'fight_history', type_='foreignkey')
    op.drop_constraint(op.f('fight_history_loser_id_fkey'), 'fight_history', type_='foreignkey')
    op.create_foreign_key(None, 'fight_history', 'profiles', ['loser_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'fight_history', 'profiles', ['winner_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('guilds_leader_id_fkey'), 'guilds', type_='foreignkey')
    op.create_foreign_key(None, 'guilds', 'profiles', ['leader_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('history_purchase_items_user_id_fkey'), 'history_purchase_items', type_='foreignkey')
    op.create_foreign_key(None, 'history_purchase_items', 'profiles', ['user_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('history_receiving_cards_user_id_fkey'), 'history_receiving_cards', type_='foreignkey')
    op.create_foreign_key(None, 'history_receiving_cards', 'profiles', ['user_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('sale_user_cards_buyer_id_fkey'), 'sale_user_cards', type_='foreignkey')
    op.drop_constraint(op.f('sale_user_cards_salesman_id_fkey'), 'sale_user_cards', type_='foreignkey')
    op.create_foreign_key(None, 'sale_user_cards', 'profiles', ['buyer_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'sale_user_cards', 'profiles', ['salesman_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('teams_template_for_battle_event_user_id_fkey'), 'teams_template_for_battle_event', type_='foreignkey')
    op.create_foreign_key(None, 'teams_template_for_battle_event', 'profiles', ['user_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('transactions_user_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'profiles', ['user_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('upgrade_items_users_in_inventory_owner_id_fkey'), 'upgrade_items_users_in_inventory', type_='foreignkey')
    op.create_foreign_key(None, 'upgrade_items_users_in_inventory', 'profiles', ['owner_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('users_inventory_owner_id_fkey'), 'users_inventory', type_='foreignkey')
    op.create_foreign_key(None, 'users_inventory', 'profiles', ['owner_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_inventory', type_='foreignkey')
    op.create_foreign_key(op.f('users_inventory_owner_id_fkey'), 'users_inventory', 'guilds', ['owner_id'], ['id'])
    op.drop_constraint(None, 'upgrade_items_users_in_inventory', type_='foreignkey')
    op.create_foreign_key(op.f('upgrade_items_users_in_inventory_owner_id_fkey'), 'upgrade_items_users_in_inventory', 'guilds', ['owner_id'], ['id'])
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_user_id_fkey'), 'transactions', 'guilds', ['user_id'], ['id'])
    op.drop_constraint(None, 'teams_template_for_battle_event', type_='foreignkey')
    op.create_foreign_key(op.f('teams_template_for_battle_event_user_id_fkey'), 'teams_template_for_battle_event', 'guilds', ['user_id'], ['id'])
    op.drop_constraint(None, 'sale_user_cards', type_='foreignkey')
    op.drop_constraint(None, 'sale_user_cards', type_='foreignkey')
    op.create_foreign_key(op.f('sale_user_cards_salesman_id_fkey'), 'sale_user_cards', 'guilds', ['salesman_id'], ['id'])
    op.create_foreign_key(op.f('sale_user_cards_buyer_id_fkey'), 'sale_user_cards', 'guilds', ['buyer_id'], ['id'])
    op.drop_constraint(None, 'history_receiving_cards', type_='foreignkey')
    op.create_foreign_key(op.f('history_receiving_cards_user_id_fkey'), 'history_receiving_cards', 'guilds', ['user_id'], ['id'])
    op.drop_constraint(None, 'history_purchase_items', type_='foreignkey')
    op.create_foreign_key(op.f('history_purchase_items_user_id_fkey'), 'history_purchase_items', 'guilds', ['user_id'], ['id'])
    op.drop_constraint(None, 'guilds', type_='foreignkey')
    op.create_foreign_key(op.f('guilds_leader_id_fkey'), 'guilds', 'users', ['leader_id'], ['id'])
    op.drop_constraint(None, 'fight_history', type_='foreignkey')
    op.drop_constraint(None, 'fight_history', type_='foreignkey')
    op.create_foreign_key(op.f('fight_history_loser_id_fkey'), 'fight_history', 'guilds', ['loser_id'], ['id'])
    op.create_foreign_key(op.f('fight_history_winner_id_fkey'), 'fight_history', 'guilds', ['winner_id'], ['id'])
    op.drop_constraint(None, 'favorite_users', type_='foreignkey')
    op.drop_constraint(None, 'favorite_users', type_='foreignkey')
    op.create_foreign_key(op.f('favorite_users_user_id_fkey'), 'favorite_users', 'guilds', ['user_id'], ['id'])
    op.create_foreign_key(op.f('favorite_users_favorite_user_id_fkey'), 'favorite_users', 'guilds', ['favorite_user_id'], ['id'])
    op.drop_constraint(None, 'battle_event_participants', type_='foreignkey')
    op.create_foreign_key(op.f('battle_event_participants_user_id_fkey'), 'battle_event_participants', 'guilds', ['user_id'], ['id'])
    op.drop_constraint(None, 'amulets_in_inventory', type_='foreignkey')
    op.create_foreign_key(op.f('amulets_in_inventory_owner_id_fkey'), 'amulets_in_inventory', 'guilds', ['owner_id'], ['id'])
    # ### end Alembic commands ###
